// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (name)
VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateGame(ctx context.Context, name string) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame, name)
	var i Game
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT
    id,
    name
FROM games
WHERE id = ?
`

func (q *Queries) GetGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i Game
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
