// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Access struct {
	GameID   int64
	PlayerID int64
}

type Game struct {
	ID   int64
	Name string
}

type Interaction struct {
	ID         int64
	GameID     int64
	PlayerID   int64
	Action     string
	OccurredAt string
}

type Player struct {
	ID             int64
	Name           string
	Username       string
	HashedPassword string
}
