// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package database

import (
	"context"
)

const grantPlayerAccess = `-- name: GrantPlayerAccess :one
INSERT INTO access (game_id, player_id)
VALUES (?, ?)
RETURNING game_id, player_id
`

type GrantPlayerAccessParams struct {
	GameID   int64
	PlayerID int64
}

func (q *Queries) GrantPlayerAccess(ctx context.Context, arg GrantPlayerAccessParams) (Access, error) {
	row := q.db.QueryRowContext(ctx, grantPlayerAccess, arg.GameID, arg.PlayerID)
	var i Access
	err := row.Scan(&i.GameID, &i.PlayerID)
	return i, err
}

const revokePlayerAccess = `-- name: RevokePlayerAccess :exec
DELETE FROM access
WHERE game_id = ? AND player_id = ?
`

type RevokePlayerAccessParams struct {
	GameID   int64
	PlayerID int64
}

func (q *Queries) RevokePlayerAccess(ctx context.Context, arg RevokePlayerAccessParams) error {
	_, err := q.db.ExecContext(ctx, revokePlayerAccess, arg.GameID, arg.PlayerID)
	return err
}
