// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package database

import (
	"context"
	"database/sql"
)

const pauseGame = `-- name: PauseGame :one
INSERT INTO interactions 
(
    game_id, 
    player_id, 
    action, 
    occurred_at
)
VALUES (?, ?, 'paused', ?)
RETURNING id, game_id, player_id, action, occurred_at
`

type PauseGameParams struct {
	GameID     int64
	PlayerID   sql.NullInt64
	OccurredAt string
}

type PauseGameRow struct {
	ID         int64
	GameID     int64
	PlayerID   sql.NullInt64
	Action     string
	OccurredAt string
}

func (q *Queries) PauseGame(ctx context.Context, arg PauseGameParams) (PauseGameRow, error) {
	row := q.db.QueryRowContext(ctx, pauseGame, arg.GameID, arg.PlayerID, arg.OccurredAt)
	var i PauseGameRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.Action,
		&i.OccurredAt,
	)
	return i, err
}

const resumeGame = `-- name: ResumeGame :one
INSERT INTO interactions 
(
    game_id, 
    player_id, 
    action, 
    occurred_at
)
VALUES (?, ?, 'resumed', ?)
RETURNING id, game_id, player_id, action, occurred_at
`

type ResumeGameParams struct {
	GameID     int64
	PlayerID   sql.NullInt64
	OccurredAt string
}

type ResumeGameRow struct {
	ID         int64
	GameID     int64
	PlayerID   sql.NullInt64
	Action     string
	OccurredAt string
}

func (q *Queries) ResumeGame(ctx context.Context, arg ResumeGameParams) (ResumeGameRow, error) {
	row := q.db.QueryRowContext(ctx, resumeGame, arg.GameID, arg.PlayerID, arg.OccurredAt)
	var i ResumeGameRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.Action,
		&i.OccurredAt,
	)
	return i, err
}

const saveGame = `-- name: SaveGame :one
INSERT INTO interactions 
(
    game_id, 
    player_id, 
    action, 
    occurred_at, 
    saved_by
)
VALUES (?, ?, 'saved', ?, ?)
RETURNING id, game_id, player_id, action, occurred_at, saved_by
`

type SaveGameParams struct {
	GameID     int64
	PlayerID   sql.NullInt64
	OccurredAt string
	SavedBy    sql.NullInt64
}

func (q *Queries) SaveGame(ctx context.Context, arg SaveGameParams) (Interaction, error) {
	row := q.db.QueryRowContext(ctx, saveGame,
		arg.GameID,
		arg.PlayerID,
		arg.OccurredAt,
		arg.SavedBy,
	)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.Action,
		&i.OccurredAt,
		&i.SavedBy,
	)
	return i, err
}
