// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package database

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (name)
VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateGame(ctx context.Context, name string) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame, name)
	var i Game
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games
WHERE id = ?
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGame, id)
	return err
}

const updateGame = `-- name: UpdateGame :exec
UPDATE games
SET name = ?
WHERE id = ?
`

type UpdateGameParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) error {
	_, err := q.db.ExecContext(ctx, updateGame, arg.Name, arg.ID)
	return err
}
