// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interactions.sql

package database

import (
	"context"
	"database/sql"
)

const addInteraction = `-- name: AddInteraction :one
INSERT INTO interactions (
    game_id,
    player_id,
    action,
    occurred_at
)
VALUES (?, ?, ?, ?)
RETURNING id, game_id, player_id, action, occurred_at
`

type AddInteractionParams struct {
	GameID     int64
	PlayerID   sql.NullInt64
	Action     string
	OccurredAt string
}

type AddInteractionRow struct {
	ID         int64
	GameID     int64
	PlayerID   sql.NullInt64
	Action     string
	OccurredAt string
}

func (q *Queries) AddInteraction(ctx context.Context, arg AddInteractionParams) (AddInteractionRow, error) {
	row := q.db.QueryRowContext(ctx, addInteraction,
		arg.GameID,
		arg.PlayerID,
		arg.Action,
		arg.OccurredAt,
	)
	var i AddInteractionRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.Action,
		&i.OccurredAt,
	)
	return i, err
}
