// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package database

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name, username, hashed_password)
VALUES (?, ?, ?)
RETURNING id, name, username, hashed_password
`

type CreatePlayerParams struct {
	Name           string
	Username       string
	HashedPassword string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.Name, arg.Username, arg.HashedPassword)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players
WHERE id = ?
`

func (q *Queries) DeletePlayer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayer, id)
	return err
}

const getPlayer = `-- name: GetPlayer :one
SELECT
    id,
    name,
    username,
    hashed_password
FROM players
WHERE id = ?
`

func (q *Queries) GetPlayer(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT
    id,
    name,
    username,
    hashed_password
FROM players
WHERE username = ?
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByUsername, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}

const updatePlayerName = `-- name: UpdatePlayerName :exec
UPDATE players
SET name = ?
WHERE id = ?
`

type UpdatePlayerNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdatePlayerName(ctx context.Context, arg UpdatePlayerNameParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerName, arg.Name, arg.ID)
	return err
}

const updatePlayerPassword = `-- name: UpdatePlayerPassword :exec
UPDATE players
SET hashed_password = ?
WHERE id = ?
`

type UpdatePlayerPasswordParams struct {
	HashedPassword string
	ID             int64
}

func (q *Queries) UpdatePlayerPassword(ctx context.Context, arg UpdatePlayerPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePlayerPassword, arg.HashedPassword, arg.ID)
	return err
}
