name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - run: go test ./...

      - run: go build -o keepitup ./cmd/server

      - uses: actions/upload-artifact@v4
        with:
          name: keepitup
          path: keepitup